### ISSUE TITLE
shadowrocket  配置了模块为啥使用不了

### ISSUE THREAD

**Issue by gentlebreeze1** [Yuheng0101/X#11]
如题

**Comment by Yuheng0101** [comment]
你说的这么笼统，我怎么解答呢？

**Comment by gentlebreeze1** [comment]
![AE31F4CF-A167-4E8D-8AE1-E72E547767DE](https://github.com/Yuheng0101/X/assets/27668596/1d951bf1-a560-4110-9583-5f333af7a016)
![611A1DCD-2056-4304-B1F4-01DE3A60EBE4](https://github.com/Yuheng0101/X/assets/27668596/d10481b7-b0fb-4f19-9197-e95e4227a669)我不是很懂这方面我就配了上边两个地方，火箭的配置文件是从vpn那里直接下载的，我还应该怎么操作请问

**Comment by Yuheng0101** [comment]
![FFEBB66A-E30B-46F4-819B-6EE4215B7610](https://github.com/Yuheng0101/X/assets/50571734/cad007b1-c4ba-4e8f-ab0a-45b50cc4ca89)
配置-HTTPS解密-检查是否未安装并且信任证书

**Comment by gentlebreeze1** [comment]
![43835D0B-C5D2-401D-9855-11E2EB22CB9D](https://github.com/Yuheng0101/X/assets/27668596/c229883c-900c-46a5-8771-6c8432ab9f41)
安装了证书并信任还是不太行  还可能是哪里的问题呢

**Comment by Yuheng0101** [comment]
连接是走[配置]吗？

**Comment by gentlebreeze1** [comment]
Https需要添加域名么？ 是走的配置

**Comment by Yuheng0101** [comment]
应该是不需要的，小火箭的规则我也不常用，我就昨天试了下。
1.添加模块
2.安装HTTPS证书并信任
3.配置直连
4.设置配置连接
这样运行是没问题的，再不行请尝试更换节点，或者使用其他代理工具。
