### ISSUE TITLE
更新之后无每日电量信息

### ISSUE THREAD

**Issue by cbdog94** [Yuheng0101/X#21]
用了最新的脚本后，没有7天内的每日电量了。不知道是把这个功能删了，还是设置不对。非常喜欢这个功能。

**Comment by MrQQQQQQQQQQ** [comment]
想问一下 新版脚本如果获取 openid和 auth 信息呢，国网 app 开启抓包软件 会提示 使用了代理，无法抓包。

**Comment by shuijiao1** [comment]
没有每日电量

**Comment by Yuheng0101** [comment]
web 端已解决，小程序已经修改策略的无法用之前的方法
