### ISSUE TITLE
4ksj在surge里运行显示错误

### ISSUE THREAD

**Issue by detesion** [Yuheng0101/X#23]
在boxjs里头配置好运行出现错误，返回错误如图
![IMG_6114](https://github.com/Yuheng0101/X/assets/95861898/1d627254-d8c5-4a59-bab9-efe1eaf1821a)

**Comment by detesion** [comment]
这个要怎么解决呢？

**Comment by Yuheng0101** [comment]
更新Surge

**Comment by detesion** [comment]
> 更新Surge

好滴好滴，感谢

**Comment by detesion** [comment]
还有个问题，可不可以增加一个bark推送，surge的信息太多容易看不到，谢谢author

**Comment by Yuheng0101** [comment]
忘记回复，脚本支持青龙，青龙可以设置bark推送。

**Comment by detesion** [comment]
是在你的脚本里头配置bark，还是青龙会自动发送bark信息

**Comment by Yuheng0101** [comment]
青龙通知里配置

**Comment by detesion** [comment]
好滴，感谢

**Comment by detesion** [comment]
> 青龙通知里配置

还有点小问题
<img width="991" alt="image" src="https://github.com/Yuheng0101/X/assets/95861898/ca0e0d79-466e-40d2-be73-b40a017e22fe">

**Comment by Yuheng0101** [comment]
自行修改相对位置

**Comment by detesion** [comment]
<img width="211" alt="image" src="https://github.com/Yuheng0101/X/assets/95861898/f9acd9b3-48b4-493b-993c-f05fce337344">
你是说这个文件的位置吗

**Comment by Yuheng0101** [comment]
相对与你存放当前脚本的路径，同目录就是./xxx

**Comment by detesion** [comment]
修改过了，现在显示的是编码不正确，但是我看了下文件的编码的确是utf8的
<img width="1679" alt="image" src="https://github.com/Yuheng0101/X/assets/95861898/a495e676-a003-40a2-b10f-562f6c1c4f10">

**Comment by detesion** [comment]
// 在脚本顶部引入 iconv-lite
const iconv = require('iconv-lite');

// console.log(options)
const promise = new Promise((resolve, reject) => {
    $[method](options, (err, response, data) => {
        if (err) {
            let errorMsg = ''
            if (response) {
                // errorMsg = `状态码: ${response.statusCode}`
                $.log(`状态码: ${response.statusCode}`)
            }
            if (data) {
                errorMsg += $.toObj(data)?.message || data
            }
            $.log(`请求接口: ${u} 异常: ${errorMsg}`)
            reject(errorMsg)
        } else {
            const _decode = (response) => {
                const buffer = response.rawBody ?? response.body;
                return iconv.decode(Buffer.from(buffer), $.encoding);
            }
            resolve(
                resultType === 'buffer'
                    ? $.isQuanX()
                        ? response.body
                        : _decode(response)
                    : resultType === 'response'
                    ? response
                    : $.toObj(data) || data
            )
        }
    })
})

**Comment by detesion** [comment]
// 在脚本顶部引入 iconv-lite
const iconv = require('iconv-lite');

// console.log(options)
const promise = new Promise((resolve, reject) => {
    $[method](options, (err, response, data) => {
        if (err) {
            let errorMsg = ''
            if (response) {
                // errorMsg = `状态码: ${response.statusCode}`
                $.log(`状态码: ${response.statusCode}`)
            }
            if (data) {
                errorMsg += $.toObj(data)?.message || data
            }
            $.log(`请求接口: ${u} 异常: ${errorMsg}`)
            reject(errorMsg)
        } else {
            const _decode = (response) => {
                const buffer = response.rawBody ?? response.body;
                return iconv.decode(Buffer.from(buffer), $.encoding);
            }
            resolve(
                resultType === 'buffer'
                    ? $.isQuanX()
                        ? response.body
                        : _decode(response)
                    : resultType === 'response'
                    ? response
                    : $.toObj(data) || data
            )
        }
    })
})

// 其他代码...

**Comment by detesion** [comment]
自己解决了emmm

**Comment by Yuheng0101** [comment]
🐉这个问题是因为版本吗，我也看见好几个同样问题的小伙伴，不过我本地Node跑没问题。
