### ISSUE TITLE
网上国网，验证绑定失败

### ISSUE THREAD

**Issue by JasonLxj** [Yuheng0101/X#28]
![image](https://github.com/Yuheng0101/X/assets/15604758/d80feb87-d283-4931-9923-98e9ec446188)

**Comment by Yuheng0101** [comment]
本身是否绑定户号？

**Comment by JasonLxj** [comment]
从 我的  我的户号 然后点击去户号，显示的是 已经绑定（底部按钮为 解除绑定）

**Comment by Yuheng0101** [comment]
BoxJS中清理一下相关缓存，再次运行试一下。

**Comment by eocene317** [comment]
![IMG_6772](https://github.com/Yuheng0101/X/assets/21039666/9198f569-5e63-498a-af9b-04e1b0b62305)
验证码识别失败怎么办

**Comment by Yuheng0101** [comment]
多试几次
