### ISSUE TITLE
查询验证卡住了

### ISSUE THREAD

**Issue by yx159247** [Yuheng0101/X#29]
大佬，请问一下这种情况是啥原因呀，一直卡在验证绑定这儿
![539B5FA6-3FE4-4D1B-9638-6D2DA63E14E0](https://github.com/Yuheng0101/X/assets/78630698/906ba6c6-9041-4cbb-99e5-63ccb4fd4aaf)

**Comment by Yuheng0101** [comment]
> 😭

没法模拟你的操作，把缓存清点试试，还是不行的话,飞机私信我账密我模拟一下。
