### ISSUE TITLE
i茅台报错

### ISSUE THREAD

**Issue by jaychoubaby** [Yuheng0101/X#3]
![image](https://github.com/Yuheng0101/X/assets/26641387/daee1a5b-f7dc-4c13-a300-80ecbd8725d9)

userid也抓到了，boxjs配置好了，执行的报错

**Comment by jaychoubaby** [comment]
填不同的地址经纬度获取到的都是同一个

**Comment by jaychoubaby** [comment]
`if (!location) await queryAddress()`

此处获取一次经纬度之后，即使修改了地址也不会重新获取

**Comment by Raphael689** [comment]
loon报错，imaotai_params ，loon抓包得到的里面的key是小写的，

**Comment by Yuheng0101** [comment]
没有在Loon和Surge上调试，有空我会测试下，谢谢反馈。
