### ISSUE TITLE
网上国网surge panel失效

### ISSUE THREAD

**Issue by bytxk** [Yuheng0101/X#31]
按照使用说明配置了surge panle
[Panel]
策略面板 = script-name=网上国网,update-interval=7200
[Script]
网上国网 = type=cron,cronexp=0 5 21 * * *,wake-system=1,script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Tasks/95598/95598.js,timeout=60

配置了之后surge panel没有内容，但是surge通知可以正常显示

**Comment by Yuheng0101** [comment]
写了，弃用了
