### ISSUE TITLE
网易云的解锁脚本好像不能用了？

### ISSUE THREAD

**Issue by jianh-ai** [Yuheng0101/X#34]
是我的问题吗？

**Comment by Yuheng0101** [comment]
已更新

**Comment by jianh-ai** [comment]
网易云的又不行了😭

**Comment by Yuheng0101** [comment]
正常用

**Comment by PaTTeeL** [comment]
看了一下
`^https?:\/\/(?:ipv4|interface\d?)\.music\.163\.com\/e?api\/(mine\/(collect|rn)\/header\/info|v\d\/user\/detail\/\d+|vipnewcenter\/app\/resource\/newaccountpage|music-vip-membership\/(client|front)\/vip\/info|batch|playlist\/privilege|search\/complex\/page|v\d\/(discovery\/recommend\/songs|playlist\/detail))`
合并成下面这样没问题吧？
`^https?://(?:ipv4|interface\d?)\.music\.163\.com/e?api/(batch|mine/(collect|rn)/header/info|music-vip-membership/(client|front)/vip/info|playlist/privilege|search/complex/page|vipnewcenter/app/resource/newaccountpage|v\d/(discovery/recommend/songs|playlist/detail|user/detail/\d+))`

另外如果域名里有ipv4字段的话，MITM是不是要增加ipv4.music.163.com了？或者干脆用*.music.163.com？
