### ISSUE TITLE
佬，青龙怎么用

### ISSUE THREAD

**Issue by shangjiazi** [Yuheng0101/X#36]
青龙运行提示跳转到boxjs配置账号密码，，，
怎么把账号密码写进代码里，望赐教，不胜感激

**Comment by Yuheng0101** [comment]
...你提问麻烦定位到某个脚本,每个脚本的变量是不一样的，一般都会在脚本注释中提到，青龙自行添加环境变量即可。

**Comment by shangjiazi** [comment]
> ...你提问麻烦定位到某个脚本,每个脚本的变量是不一样的，一般都会在脚本注释中提到，青龙自行添加环境变量即可。
@Yuheng0101 
佬，Tasks/95598/95598.js，这个脚本，我也添加环境变量了，运行提示
请先配置网上国网账号密码!
点击前往BoxJs配置
点击跳转

我的配置如下
export 95598_username=
export 95598_password=

**Comment by Yuheng0101** [comment]
WSGW_USERNAME 、WSGW_PASSWORD 、WSGW_RECENT_ELC_FEE (是否展示最近用电) 、WSGW_NOTIFY_ALL (是否通知所有户号, 默认只展示默认户号)。
