### ISSUE TITLE
push+发送一对一推送失败

### ISSUE THREAD

**Issue by RagBagCN** [Yuheng0101/X#9]
https://github.com/Yuheng0101/X/blame/cb185f124c91d04b2d35f20b2024ccef26124425/Tasks/95598/95598.js#L629

问题描述：“push+发送一对一通知消息失败：标题不能换行”
问题解决：将`await o.sendNotify(${t}\n${n}, c)`中的`/n`取消或者改为`/t`
![image](https://github.com/Yuheng0101/X/assets/73032662/aba7d2e0-3e9d-4e4b-9908-9930bca33266)

**Comment by RagBagCN** [comment]
但是出现将推送内容会放在了标题里

**Comment by Yuheng0101** [comment]
自改用吧，我是用TG做的测试没啥问题，其他通知可能需要适配，谢谢反馈。

**Comment by RagBagCN** [comment]
谢谢大佬回复
